{"name": "Тестируем ошибку входа с неправильными данными.", "status": "passed", "steps": [{"name": "POST запрос к /api/auth/login с данными {'email': 'isakovavde@hotmail.com', 'password': 'WvviQdu@5p'}", "status": "passed", "start": 1760501493009, "stop": 1760501493436}], "parameters": [{"name": "test_case_id", "value": "1"}], "start": 1760501493009, "stop": 1760501493440, "uuid": "15a81c32-5fa2-4136-8e1d-cf196659de5f", "historyId": "718055d33a25ba946c8e26ade583342a", "testCaseId": "e8f57114dc52a20f94d85eddecf030ca", "fullName": "tests.test_login_user.UserAuthenticationTests#test_login_user_wrong_credentials", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_user"}, {"name": "subSuite", "value": "UserAuthenticationTests"}, {"name": "host", "value": "DESKTOP-6FU1OQK"}, {"name": "thread", "value": "12712-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}], "titlePath": ["tests", "test_login_user.py", "UserAuthenticationTests"]}