{"name": "Тестируем ошибку входа с неправильными данными.", "status": "passed", "steps": [{"name": "POST запрос к /api/auth/login с данными {'email': 'burovjuli@yandex.ru', 'password': 'uvMDyGU4wW'}", "status": "passed", "start": 1760501892281, "stop": 1760501892688}], "parameters": [{"name": "test_case_id", "value": "1"}], "start": 1760501892281, "stop": 1760501892691, "uuid": "10611657-8503-4a72-944a-8979a028a6ee", "historyId": "718055d33a25ba946c8e26ade583342a", "testCaseId": "e8f57114dc52a20f94d85eddecf030ca", "fullName": "tests.test_login_user.UserAuthenticationTests#test_login_user_wrong_credentials", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_user"}, {"name": "subSuite", "value": "UserAuthenticationTests"}, {"name": "host", "value": "DESKTOP-6FU1OQK"}, {"name": "thread", "value": "908-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}], "titlePath": ["tests", "test_login_user.py", "UserAuthenticationTests"]}